// <auto-generated />
using System;
using LocadoraAutomoveis.Infra.Orm.Compartilhado;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LocadoraAutomoveis.Infra.Orm.Migrations
{
    [DbContext(typeof(LocadoraAutomoveisDbContext))]
    [Migration("20230802173934_Parceiros")]
    partial class Parceiros
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LocadoraAutomoveis.Dominio.ModuloCuponsParceiros.Cupom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("parceiroId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("parceiroId");

                    b.ToTable("Cupom");
                });

            modelBuilder.Entity("LocadoraAutomoveis.Dominio.ModuloCuponsParceiros.Parceiro", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TBParceiros", (string)null);
                });

            modelBuilder.Entity("LocadoraAutomoveis.Dominio.ModuloCuponsParceiros.Cupom", b =>
                {
                    b.HasOne("LocadoraAutomoveis.Dominio.ModuloCuponsParceiros.Parceiro", "parceiro")
                        .WithMany("Cupoms")
                        .HasForeignKey("parceiroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("parceiro");
                });

            modelBuilder.Entity("LocadoraAutomoveis.Dominio.ModuloCuponsParceiros.Parceiro", b =>
                {
                    b.Navigation("Cupoms");
                });
#pragma warning restore 612, 618
        }
    }
}
